name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install pipenv
        run: pipx install pipenv
      - name: Install dependencies
        run: pipenv install --dev --deploy
      - name: Run tests
        run: pipenv run pytest -q


